-- ═══════════════════════════════════════════════════════════════════════════
-- Seed: realistic dummy bookings + customers
-- ═══════════════════════════════════════════════════════════════════════════
-- Uses CTEs to grab real boat/beach-house IDs from the DB so FKs are valid.
-- Safe to run multiple times (INSERT ... ON CONFLICT DO NOTHING).
-- ═══════════════════════════════════════════════════════════════════════════

do $$
declare
  boat1_id        uuid;
  boat2_id        uuid;
  house1_id       uuid;
  house2_id       uuid;

  cust1_id  uuid := gen_random_uuid();
  cust2_id  uuid := gen_random_uuid();
  cust3_id  uuid := gen_random_uuid();
  cust4_id  uuid := gen_random_uuid();
  cust5_id  uuid := gen_random_uuid();
  cust6_id  uuid := gen_random_uuid();

  bk1_id    uuid := gen_random_uuid();
  bk2_id    uuid := gen_random_uuid();
  bk3_id    uuid := gen_random_uuid();
  bk4_id    uuid := gen_random_uuid();
  bk5_id    uuid := gen_random_uuid();
  bk6_id    uuid := gen_random_uuid();
  bk7_id    uuid := gen_random_uuid();
  bk8_id    uuid := gen_random_uuid();
  bk9_id    uuid := gen_random_uuid();
  bk10_id   uuid := gen_random_uuid();

begin

  -- Grab the first two boats and beach houses (if they exist).
  select id into boat1_id  from public.boats         order by created_at asc limit 1 offset 0;
  select id into boat2_id  from public.boats         order by created_at asc limit 1 offset 1;
  select id into house1_id from public.beach_houses  order by created_at asc limit 1 offset 0;
  select id into house2_id from public.beach_houses  order by created_at asc limit 1 offset 1;

  -- ── Customers ───────────────────────────────────────────────────────────

  insert into public.customers
    (id, full_name, email, phone, marketing_opt_in, total_bookings, total_spent, last_booking_at)
  values
    (cust1_id, 'Adaeze Okonkwo',   'adaeze.okonkwo@gmail.com',    '+2348012345678', true,  3, 1350000, now() - interval '2 days'),
    (cust2_id, 'Emeka Nwosu',      'emeka.nwosu@yahoo.com',       '+2348023456789', false, 2,  720000, now() - interval '5 days'),
    (cust3_id, 'Fatima Bello',     'fatima.bello@outlook.com',    '+2348034567890', true,  1,  480000, now() - interval '10 days'),
    (cust4_id, 'Chidi Okafor',     'chidi.okafor@gmail.com',      '+2348045678901', true,  4, 2200000, now() - interval '1 day'),
    (cust5_id, 'Ngozi Eze',        'ngozi.eze@hotmail.com',       '+2348056789012', false, 1,  360000, now() - interval '14 days'),
    (cust6_id, 'Babatunde Lawal',  'babs.lawal@gmail.com',        '+2348067890123', true,  2,  900000, now() - interval '7 days')
  on conflict do nothing;

  -- ── Bookings ─────────────────────────────────────────────────────────────
  -- reference_code is auto-generated by trigger; we just omit it.

  -- 1. Confirmed boat cruise (past) ----------------------------------------
  insert into public.bookings
    (id, booking_type, boat_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date, start_time, end_time,
     total_amount, status, payment_status, source, notes)
  select bk1_id, 'boat_cruise', boat1_id, cust1_id,
         'Adaeze Okonkwo', 'adaeze.okonkwo@gmail.com', '+2348012345678',
         8,
         current_date - 14, current_date - 14,
         '10:00', '16:00',
         480000, 'confirmed', 'paid', 'web',
         'Birthday celebration — requested champagne on arrival.'
  where boat1_id is not null
  on conflict do nothing;

  -- 2. Confirmed boat cruise (upcoming) ----------------------------------------
  insert into public.bookings
    (id, booking_type, boat_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date, start_time, end_time,
     total_amount, status, payment_status, source)
  select bk2_id, 'boat_cruise', boat1_id, cust4_id,
         'Chidi Okafor', 'chidi.okafor@gmail.com', '+2348045678901',
         12,
         current_date + 5, current_date + 5,
         '09:00', '15:00',
         600000, 'confirmed', 'paid', 'admin'
  where boat1_id is not null
  on conflict do nothing;

  -- 3. Pending boat cruise (tomorrow) -------------------------------------------
  insert into public.bookings
    (id, booking_type, boat_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date, start_time, end_time,
     total_amount, status, payment_status, source, notes)
  select bk3_id, 'boat_cruise', boat2_id, cust2_id,
         'Emeka Nwosu', 'emeka.nwosu@yahoo.com', '+2348023456789',
         6,
         current_date + 1, current_date + 1,
         '14:00', '18:00',
         320000, 'pending', 'pending', 'web',
         'Client requested sunset cruise — needs confirmation.'
  where boat2_id is not null
  on conflict do nothing;

  -- 4. Beach house stay — confirmed (past) -------------------------------------
  insert into public.bookings
    (id, booking_type, beach_house_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date,
     total_amount, status, payment_status, source)
  select bk4_id, 'beach_house', house1_id, cust1_id,
         'Adaeze Okonkwo', 'adaeze.okonkwo@gmail.com', '+2348012345678',
         4,
         current_date - 21, current_date - 18,
         450000, 'confirmed', 'paid', 'web'
  where house1_id is not null
  on conflict do nothing;

  -- 5. Beach house stay — upcoming ---------------------------------------------
  insert into public.bookings
    (id, booking_type, beach_house_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date,
     total_amount, status, payment_status, source, notes)
  select bk5_id, 'beach_house', house1_id, cust4_id,
         'Chidi Okafor', 'chidi.okafor@gmail.com', '+2348045678901',
         6,
         current_date + 10, current_date + 13,
         720000, 'confirmed', 'paid', 'admin',
         'VIP guest. Ensure property is fully stocked before arrival.'
  where house1_id is not null
  on conflict do nothing;

  -- 6. Beach house stay + transport (outbound) — parent booking ----------------
  insert into public.bookings
    (id, booking_type, beach_house_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date,
     total_amount, status, payment_status, source)
  select bk6_id, 'beach_house', house2_id, cust6_id,
         'Babatunde Lawal', 'babs.lawal@gmail.com', '+2348067890123',
         3,
         current_date + 3, current_date + 6,
         540000, 'confirmed', 'paid', 'web'
  where house2_id is not null
  on conflict do nothing;

  -- 6b. Transport sub-booking linked to above ----------------------------------
  insert into public.bookings
    (id, booking_type, beach_house_id, parent_beach_house_booking_id, customer_id,
     customer_name, customer_email, customer_phone, guest_count,
     start_date, end_date, start_time, end_time,
     transport_type, total_amount, status, payment_status, source)
  select bk7_id, 'transport', house2_id, bk6_id, cust6_id,
         'Babatunde Lawal', 'babs.lawal@gmail.com', '+2348067890123', 3,
         current_date + 3, current_date + 3, '08:00', '10:00',
         'outbound',
         60000, 'confirmed', 'paid', 'web'
  where house2_id is not null
  on conflict do nothing;

  -- 7. Cancelled booking -------------------------------------------------------
  insert into public.bookings
    (id, booking_type, boat_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date, start_time, end_time,
     total_amount, status, payment_status, source, notes)
  select bk8_id, 'boat_cruise', boat1_id, cust3_id,
         'Fatima Bello', 'fatima.bello@outlook.com', '+2348034567890',
         5,
         current_date + 2, current_date + 2,
         '11:00', '15:00',
         400000, 'cancelled', 'failed', 'web',
         'Customer requested cancellation — full refund issued.'
  where boat1_id is not null
  on conflict do nothing;

  -- 8. Pending beach house — payment not yet received --------------------------
  insert into public.bookings
    (id, booking_type, beach_house_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date,
     total_amount, status, payment_status, source)
  select bk9_id, 'beach_house', house2_id, cust5_id,
         'Ngozi Eze', 'ngozi.eze@hotmail.com', '+2348056789012',
         2,
         current_date + 20, current_date + 23,
         360000, 'pending', 'pending', 'mobile'
  where house2_id is not null
  on conflict do nothing;

  -- 9. Admin-created boat booking (future) ------------------------------------
  insert into public.bookings
    (id, booking_type, boat_id, customer_id, customer_name, customer_email,
     customer_phone, guest_count, start_date, end_date, start_time, end_time,
     total_amount, status, payment_status, source, notes)
  select bk10_id, 'boat_cruise', boat2_id, cust4_id,
         'Chidi Okafor', 'chidi.okafor@gmail.com', '+2348045678901',
         10,
         current_date + 15, current_date + 15,
         '10:00', '18:00',
         800000, 'confirmed', 'paid', 'admin',
         'Corporate event — full day charter.'
  where boat2_id is not null
  on conflict do nothing;

end $$;
